// this file was generated by better-cmake
// window-template v0.0.1

#define window_template_NAME "window-template"
#define window_template_AUTHOR "DaemonTsun"
#define window_template_VERSION "0.0.1"
#define window_template_VERSION_MAJOR 0
#define window_template_VERSION_MINOR 0
#define window_template_VERSION_PATCH 1
